### PR TITLE
Added basic tests for version and auth_test.

### PR DESCRIPTION
**Pull request by dblock**
Beginning of https://github.com/aki017/slack-ruby-gem/issues/8, using VCR.

Enable Travis-CI in https://travis-ci.org/profile before merging this. Here's a build: https://travis-ci.org/dblock/slack-ruby-gem/builds/60445667

### CODE REVIEW

**Comment by aki017** [comment]
I working on spec branch to write :sweat:
pls check it

**Comment by dblock** [comment]
Oh. That can be merged on top or vice-versa, what do you want me to do? I think *any* tests is better than nothing right now, maybe no need for a branch?

**Comment by aki017** [comment]
im googling how to filter sensitive data and i learn config.filter_sensitive_data.
ok. now i merge :+1:

**Comment by dblock** [comment]
Do enable Travis-CI first!

The auth_test.yml VCR file was hand-edited to remove any passwords if that's what you mean?

**Pull request closed without merging**
