### PR TITLE
Add automatic pinging to prevent websocket closure.

### PR DESCRIPTION
**Pull request by samdoiron**
Should be a fix for https://github.com/aki017/slack-ruby-gem/issues/38

### CODE REVIEW

**Comment by dblock** [comment]
I think this shouldn't be using a thread, but a EventMachine::PeriodicTimer. At the very least the behavior of `ws.send` on a different thread is unpredictable. There's nothing about keeping the thread alive if it fails to `ws.send` either.

**Comment by dblock** [comment]
@samdoiron I would take a clean EM-based implementation for this with tests in https://github.com/dblock/slack-ruby-client, however I am not seeing this problem in bots based on [slack-ruby-bot](https://github.com/dblock/slack-ruby-bot). How do you reproduce this?

**Comment by samdoiron** [comment]
Haven't been able to reproduce, but have had the bot disconnect (stop receiving web-socket data) several times. It's also reasonable that a bot should reconnect in the case that (because of an error on slack's side or otherwise) the connection is dropped.

**Comment by dblock** [comment]
I had a `loop` in https://github.com/dblock/slack-ruby-bot/blob/master/lib/slack-ruby-bot/app.rb#L44, so this explains that. I don't think maintaining the connection in a loop belongs in this library TBH.

**Comment by samdoiron** [comment]
Makes sense that this should be managed higher up the chain. The also realized my current version doesn't work, because the connection url's expire.

I'll revert that change, but I think it still makes sense to have the socket ping every 30s, thoughts?

**Comment by dblock** [comment]
@samdoiron That makes more sense. Would you PR this into https://github.com/dblock/slack-ruby-client with a test, please?

**Pull request closed without merging**
