### PR TITLE
Request get, not post.

### PR DESCRIPTION
**Pull request by treeder**
Post doesn't work here.

### CODE REVIEW

**Comment by aki017** [comment]
sry that file is auto generated file 
https://github.com/aki017/slack-ruby-gem/pull/19/files#diff-ad8b1489f746c6d013cf6bcb88219ea4L1

**Comment by treeder** [comment]
Generated from what?  Can it be patched somewhere else?

**Comment by aki017** [comment]
That line is generated from this erb
https://github.com/aki017/slack-ruby-gem/blob/ba586e04380d77be9aea0ec8e45ed8d2b3cc033f/lib/generators/templates/method.rb.erb#L23

**Comment by treeder** [comment]
If I put a patch in to that generator for this special case will you accept it?  Do a get if it's that particular method.

**Comment by aki017** [comment]
we can use post.

**Comment by treeder** [comment]
Did they change the API?

**Comment by aki017** [comment]
maybe changed

**Pull request closed without merging**
